### ISSUE TITLE
Can't install app

### ISSUE THREAD

**Issue by marioserranorodriguez** [industrial-edge/mounting-an-nfs-share-to-ied#6] opened 2023-01-27 10:25 UTC
Hello,

I'm contacting you because I'm not able to install the NFS app on my edge device. I have imported the YAML in my Industrial Edge App Publisher. Everything seems correct when I upload the version to my IEM. But then, when I try to install the app in my IED, an error message appears and there's nothing I can do. The error message says "Host path must start with "./" or "/", and can not have "$" or "../" and can not be just "./".: Failed to install NFS". You can see that in the attached screenshot. 

![image](https://user-images.githubusercontent.com/123732534/215064014-cbbc8e76-d322-4457-9424-f3b9f57722d5.png)

Please, does anyone know what can I do?

Thanks a lot.

Kind regards,
Mario Serrano Rodríguez.

**Comment by EndyCZ** [comment] 2023-02-07 15:17
Hi Mario, I replicated the issue and reported the bug to R&D. I will let you know once I know more about the root cause analysis.

**Comment by EndyCZ** [comment] 2023-08-10 10:18
Bug should be fixed with the next release, it was much more difficult than expected. :)

**Comment by EndyCZ** [comment] 2023-09-14 02:24
Tested the functionality on the preview version. It works on IEMA 1.14.

**Closed by EndyCZ** 2023-09-14 02:24 UTC
